name = "retarglow"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]

# DO NOT use `main` or `site.entry-point` for Pages + Functions

[build]
command = "echo 'Build complete'"  # No actual build, only functions

[site]
bucket = "./"  # This prevents bucket error, even though we use no assets
