compatibility_date = "2025-06-01"
workers_dev = false

routes = [
  { pattern = "https://retarglow.com/log", script = "log" },
  { pattern = "https://retarglow.com/serve", script = "serve" },
  { pattern = "https://retarglow.com/r", script = "r" },
  { pattern = "https://retarglow.com/pixel.js", script = "pixel" }
]
