name = "retarglow"
compatibility_date = "2024-06-01"
node_compat = true
pages_build_output_dir = "./"  # Important for Pages deploy

[site]
entry-point = "."

# No [routes] section needed for Cloudflare Pages + Functions
