name = "retarglow"
compatibility_date = "2024-06-01"
node_compat = true

[site]
bucket = "./"
entry-point = "."

[[routes]]
pattern = "https://retarglow.com/pixel.js"
script = "pixel"

[[routes]]
pattern = "https://retarglow.com/log"
script = "log"

[[routes]]
pattern = "https://retarglow.com/serve"
script = "serve"

[[routes]]
pattern = "https://retarglow.com/r"
script = "redirect"
