name = "retarglow"
main = "index.js"
compatibility_date = "2025-09-04"
account_id = "c0aee4b4132b43c68bc0c5b28aabc4b7"
workers_dev = false

routes = [
  { pattern = "retarglow.com/*", zone_name = "retarglow.com" }
]
